import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import PageLayout from "./page-layout";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Globetrotter Travel Planner",
  description: "Generated by @0x1Shub",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <Providers>
          <PageLayout>
            {children}
          </PageLayout>
        </Providers>
      </body>
    </html>
  );
}